# Site settings
title: Applied Geophysics Group
email: contact@ggaunicamp.com
description: > # this means to ignore newlines until "baseurl:"
  The Applied Geophysics Group strives to create the best image
  processing techniques for the petroleum industry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gga-cepetro.github.io" # the base hostname & protocol for your site
github_username:  gga-cepetro

# Build settings
markdown: kramdown
